---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/k8s/springboot
  type: udm.Application
  lastVersion: 0.1.2
  children:
  - name: 0.1.2
    type: udm.DeploymentPackage
    deployables:
    - name: service
      type: k8s.ResourcesFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.2/service/service.json"
    - name: deployment
      type: k8s.ResourcesFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.2/deployment/deployment.json"
  - name: 0.1.3
    type: udm.DeploymentPackage
    deployables:
    - name: service
      type: k8s.ResourcesTemplateFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.3/service/service.json"
    - name: deployment
      type: k8s.ResourcesTemplateFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.3/deployment/deployment.json"
  - name: 0.1.4
    type: udm.DeploymentPackage
    deployables:
    - name: service
      type: k8s.ResourcesTemplateFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.4/service/service.yaml"
    - name: deployment
      type: k8s.ResourcesTemplateFile
      mergePatchType: strategic
      propagationPolicy: Foreground
      updateMethod: patch
      file: !file "artifacts/Applications/k8s/springboot/0.1.4/deployment/deployment.yaml"
