---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/k8s
  children:
  - name: conf.dev
    type: udm.Dictionary
    entries:
      env: dev
      k8s.ResourcesTemplate.templateNamespace: xld-k8s
      k8s.ResourcesTemplate.templateName: xld-k8s-resource-template

  - name: k8s-dev
    type: udm.Environment
    members:
    - Infrastructure/k8s/minikube/dev
    dictionaries:
    - Environments/k8s/conf.dev
